### ISSUE TITLE
Revert back to HTTPS from SPDY

### ISSUE THREAD

**Issue by mjlawrence91** [mjlawrence91/moviechooser#24]
Found when fixing #20.

Using `node-sdpy` for HTTP/2 gives this error when accessing the server:

```
internal/buffer.js:940
class FastBuffer extends Uint8Array {}
^

RangeError: Invalid typed array length: -4095
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:940:1)
    at Handle.onStreamRead [as onread] (internal/stream_base_commons.js:181:19)
    at Stream.<anonymous> (/Users/matt/Documents/Development/movie-chooser/node_modules/handle-thing/lib/handle.js:120:12)
    at Stream.emit (events.js:215:7)
    at endReadableNT (/Users/matt/Documents/Development/movie-chooser/node_modules/spdy-transport/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

Until [this issue](https://github.com/spdy-http2/handle-thing/issues/6) is resolved, reverting back to native `https` module.

**Comment by mjlawrence91** [comment]
Closing: #25 fixes this.
